#!/bin/bash
# WiFi Monitor - Complete Setup Wizard
# Interactive setup for hotspot + monitoring

set -e

GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
RED='\033[0;31m'
NC='\033[0m'

clear
echo -e "${GREEN}╔═══════════════════════════════════════════════╗${NC}"
echo -e "${GREEN}║  WiFi Monitor - Complete Setup Wizard         ║${NC}"
echo -e "${GREEN}║  Hotspot + Monitoring in One Go!              ║${NC}"
echo -e "${GREEN}╚═══════════════════════════════════════════════╝${NC}"
echo ""

# Check root
if [ "$EUID" -ne 0 ]; then
    echo -e "${RED}Please run with sudo${NC}"
    exit 1
fi

# Step 1: Gather information
echo -e "${BLUE}═══ Step 1: Configuration ═══${NC}"
echo ""
read -p "Hotspot SSID (default: WiFi-Monitor): " SSID
SSID=${SSID:-WiFi-Monitor}

read -sp "Hotspot Password (min 8 chars, default: monitor123): " PASSWORD
echo ""
PASSWORD=${PASSWORD:-monitor123}

if [ ${#PASSWORD} -lt 8 ]; then
    echo -e "${RED}Password must be at least 8 characters!${NC}"
    exit 1
fi

read -p "WiFi Channel (1-13, default: 7): " CHANNEL
CHANNEL=${CHANNEL:-7}

read -p "Internet interface (eth0 for Ethernet, usb0 for dongle, default: eth0): " INET_IF
INET_IF=${INET_IF:-eth0}

read -p "Backend server URL (e.g., http://192.168.1.100:5000/api/v1): " BACKEND_URL
if [ -z "$BACKEND_URL" ]; then
    echo -e "${RED}Backend URL is required!${NC}"
    exit 1
fi

read -p "Backend admin email: " ADMIN_EMAIL
if [ -z "$ADMIN_EMAIL" ]; then
    echo -e "${RED}Admin email is required!${NC}"
    exit 1
fi

read -sp "Backend admin password: " ADMIN_PASSWORD
echo ""
if [ -z "$ADMIN_PASSWORD" ]; then
    echo -e "${RED}Admin password is required!${NC}"
    exit 1
fi

# Confirm
echo ""
echo -e "${YELLOW}═══ Configuration Summary ═══${NC}"
echo "Hotspot SSID: $SSID"
echo "Password: ${PASSWORD:0:3}***"
echo "Channel: $CHANNEL"
echo "Internet Interface: $INET_IF"
echo "Backend URL: $BACKEND_URL"
echo "Admin Email: $ADMIN_EMAIL"
echo ""
read -p "Continue with this configuration? (y/n) " -n 1 -r
echo ""
if [[ ! $REPLY =~ ^[Yy]$ ]]; then
    echo "Setup cancelled"
    exit 0
fi

# Export for scripts
export HOTSPOT_SSID="$SSID"
export HOTSPOT_PASSWORD="$PASSWORD"
export HOTSPOT_CHANNEL="$CHANNEL"
export INTERNET_INTERFACE="$INET_IF"
export WLAN_INTERFACE="wlan0"

# Step 2: Setup hotspot
echo ""
echo -e "${BLUE}═══ Step 2: Setting up WiFi Hotspot ═══${NC}"
echo ""
bash setup-hotspot.sh
if [ $? -ne 0 ]; then
    echo -e "${RED}Hotspot setup failed! Check errors above.${NC}"
    exit 1
fi

# Step 3: Test hotspot
echo ""
echo -e "${BLUE}═══ Step 3: Testing Hotspot ═══${NC}"
echo ""
sleep 3
bash test-hotspot.sh
if [ $? -ne 0 ]; then
    echo -e "${YELLOW}Some hotspot tests failed. Review and fix before continuing.${NC}"
    read -p "Continue anyway? (y/n) " -n 1 -r
    echo ""
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        exit 1
    fi
fi

# Step 4: Install monitor agent
echo ""
echo -e "${BLUE}═══ Step 4: Installing WiFi Monitor Agent ═══${NC}"
echo ""
if [ ! -f install.sh ]; then
    echo -e "${RED}install.sh not found! Are you in the pi-agent directory?${NC}"
    exit 1
fi
bash install.sh
if [ $? -ne 0 ]; then
    echo -e "${RED}Monitor installation failed!${NC}"
    exit 1
fi

# Step 5: Configure agent
echo ""
echo -e "${BLUE}═══ Step 5: Configuring Monitor Agent ═══${NC}"
echo ""
cat > /opt/wifi-monitor/config.yaml << EOF
# WiFi Monitor Pi Agent Configuration
# Auto-generated by setup wizard

# Backend API endpoint
api_base_url: "$BACKEND_URL"

# Network interface to monitor
interface: "wlan0"

# Hotspot mode configuration
hotspot_mode: true
internet_interface: "$INET_IF"

# Authentication credentials
auth:
  email: "$ADMIN_EMAIL"
  password: "$ADMIN_PASSWORD"

# Simulation mode - PRODUCTION
simulation_mode: false

# Scan interval in seconds
scan_interval: 30

# Stats collection interval in seconds
stats_interval: 60

# Logging configuration
log_level: "INFO"
log_dir: "logs"

# Retry configuration for network operations
retry_attempts: 3
retry_delay: 5

# Simulation settings (not used in production)
simulation:
  device_count: 5
  min_bytes: 1024
  max_bytes: 104857600
EOF

chown wifi-monitor:wifi-monitor /opt/wifi-monitor/config.yaml
chmod 600 /opt/wifi-monitor/config.yaml
echo -e "${GREEN}✓ Configuration created${NC}"

# Step 6: Test configuration
echo ""
echo -e "${BLUE}═══ Step 6: Testing Configuration ═══${NC}"
echo ""
sudo -u wifi-monitor /opt/wifi-monitor/venv/bin/python3 /opt/wifi-monitor/run.py --test-config
if [ $? -ne 0 ]; then
    echo -e "${RED}Configuration test failed!${NC}"
    echo "Please check:"
    echo "  1. Backend server is running at $BACKEND_URL"
    echo "  2. Credentials are correct"
    echo "  3. Network connectivity"
    exit 1
fi

# Step 7: Enable and start service
echo ""
echo -e "${BLUE}═══ Step 7: Starting Monitor Service ═══${NC}"
echo ""
systemctl enable wifi-monitor
systemctl start wifi-monitor
sleep 3

if systemctl is-active --quiet wifi-monitor; then
    echo -e "${GREEN}✓ Monitor service is running${NC}"
else
    echo -e "${RED}✗ Monitor service failed to start${NC}"
    echo "Check logs: journalctl -u wifi-monitor -n 50"
    exit 1
fi

# Success!
echo ""
echo -e "${GREEN}╔═══════════════════════════════════════════════╗${NC}"
echo -e "${GREEN}║        Setup Complete Successfully! 🎉         ║${NC}"
echo -e "${GREEN}╚═══════════════════════════════════════════════╝${NC}"
echo ""
echo -e "${YELLOW}Your WiFi Hotspot:${NC}"
echo "  📡 SSID: $SSID"
echo "  🔑 Password: $PASSWORD"
echo "  🌐 Gateway: 192.168.50.1"
echo ""
echo -e "${YELLOW}What's Running:${NC}"
echo "  ✓ WiFi Hotspot (hostapd)"
echo "  ✓ DHCP Server (dnsmasq)"
echo "  ✓ Internet Sharing (NAT)"
echo "  ✓ WiFi Monitor Agent"
echo ""
echo -e "${YELLOW}Next Steps:${NC}"
echo "1. ${GREEN}Connect a device to '$SSID' WiFi${NC}"
echo "   - Password: $PASSWORD"
echo ""
echo "2. ${GREEN}Test internet on the device${NC}"
echo "   - Open a web browser"
echo "   - Visit any website"
echo ""
echo "3. ${GREEN}Check backend dashboard${NC}"
echo "   - Go to your backend URL"
echo "   - Device should appear within 30 seconds"
echo ""
echo -e "${YELLOW}Monitoring Commands:${NC}"
echo "  View agent logs:"
echo "    ${BLUE}journalctl -u wifi-monitor -f${NC}"
echo ""
echo "  Check hotspot status:"
echo "    ${BLUE}hotspot-status${NC}"
echo ""
echo "  See connected devices:"
echo "    ${BLUE}cat /proc/net/arp${NC}"
echo ""
echo "  View DHCP leases:"
echo "    ${BLUE}cat /var/lib/misc/dnsmasq.leases${NC}"
echo ""
echo -e "${YELLOW}Troubleshooting:${NC}"
echo "  If devices can't connect:"
echo "    ${BLUE}journalctl -u hostapd -f${NC}"
echo ""
echo "  If no internet:"
echo "    ${BLUE}bash test-hotspot.sh${NC}"
echo ""
echo "  If monitoring not working:"
echo "    ${BLUE}journalctl -u wifi-monitor -n 50${NC}"
echo ""
echo -e "${GREEN}Everything is set up and running!${NC}"
echo -e "${GREEN}Connect devices and start monitoring! 🚀${NC}"
echo ""
